### ISSUE TITLE
No data returned from query

### ISSUE THREAD

**Issue by ddonders** [adaptivethreat/BloodHound#44]
Having a try with this tool, scripts ran ok. Only noticed some occasional warnings related to converting SID's.

When starting the tool it doesn't show the Domain Admins group with memberships. Any idea what could be the cause?
Searching other users, groups, computers works fine and info is displayed. Only Domain Admins info is never shown.

If someone has an idea what is wrong feel free to drop a note.

Cheers.

**Comment by rvazarkar** [comment]
We'll have an updated ingestor coming int he next couple days, hopefully it'll help you diagnose some issues better

**Comment by HarmJ0y** [comment]
There is now a major tuneup for the ingestor at https://github.com/adaptivethreat/BloodHound/blob/ingestor_tuneup/PowerShell/BloodHound.ps1

All the enumeration and export logic was combined into Invoke-BloodHound -> by default it will output to csvs in the current directory, using -URI/-UserPass will switch to the neo4j REST ingestion instead. -CollectionMethod Stealth was heavily fixed/tuned as well.

**Comment by ddonders** [comment]
Thanks for the update, I gave it a try but it doesn't even finish.

These are my findings:

- Various memory errors popped up
- Enumeration errors
- Trusts not properly recognized
- ...

**Comment by rvazarkar** [comment]
We've pushed another update to the ingestor on the same branch. Maybe this will fix your issues?

**Comment by ddonders** [comment]
I'm still getting the No data returned from query message.

As for some statistics:
BloodHound
Users: 3810
Computers: 978
Groups: 1411
Sessions: 956
Relationships: 23956

Neo4j
Array Store: 8.00 KiB
Logical Store: 5.63 MiB
Node Store: 151.96 KiB
Property Store: 286.84 KiB
Relationship Store: 1.02 MiB
String Store Size: 112.00 KiB
Total Store Size: 7.64 MiB

**Comment by rvazarkar** [comment]
I dont know what your issue is, are you on a foreign domain or anything like that? Also, did you try the 1.1 release of BloodHound? It changes the way queries are done that will make strange names work

**Comment by rvazarkar** [comment]
No response to this, so closing
